name: Django CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          sudo apt-get install poppler-utils
          python -m pip install --upgrade pip
          pip show wheel
          pip show aws-lambda-builders
          pip install -r backend/requirements.txt
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          # Version of PostgreSQL to use
          # POSTGRES_DB - name for the default database that is created
          postgresql db: ci
          # POSTGRES_USER - create the specified user with superuser power
          postgresql user: postgres
          # POSTGRES_PASSWORD - superuser password
          postgresql password: postgres
      - name: Set up database
        run: |
          cd backend
          cp backend/.env.ci backend/.env
          ../cli/create_and_populate_database.bash
      - name: Run Associations Tests
        run: |
          cd backend
          python manage.py test associations
      - name: Run Authentication Tests
        run: |
          cd backend
          python manage.py test authentication
      - name: Run Backend Tests
        run: |
          cd backend
          python manage.py test backend
      - name: Run Polls Tests
        run: |
          cd backend
          python manage.py test polls
      - name: Run Subscription Tests
        run: |
          cd backend
          python manage.py test subscriptions
      - name: Run Tags Tests
        run: |
          cd backend
          python manage.py test tags
